name: Auto Approve paketo-bot PR

on:
  pull_request:
    branches: [ main ]
    paths: [ usns ]

jobs:
  approve:
    name: Auto Approve
    if: ${{ github.event.pull_request.user.login == 'paketo-bot' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Approve
      uses: paketo-buildpacks/github-config/actions/pull-request/approve@main
      with:
        user: paketo-bot-reviewer
        token: ${{ secrets.PAKETO_BOT_REVIEWER_GITHUB_TOKEN }}
        author: ${{ github.event.pull_request.user.login }}
        number: ${{ github.event.number }}
