name: Test USN Monitor
on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 2 * * *'
  push:
    branches: [ main ]
    paths:
    - 'actions/usn-monitor/entrypoint/**'

jobs:
  test-usn-monitor:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Run Tests
      run: |
        cd actions/usn-monitor/entrypoint
        go test ./...
