name: Trigger Releases
on:
  push:
    branches: [ main ]
    paths: [ usns ]

jobs:
  trigger-releases:
    runs-on: ubuntu-18.04

    steps:
    - name: Trigger Release
      uses: paketo-buildpacks/github-config/actions/dispatch@main
      with:
        repos: >
          paketo-buildpacks/tiny-stack-release,
          paketo-buildpacks/base-stack-release,
          paketo-buildpacks/full-stack-release
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        event: new-usn
        payload: '{}'
